export type {
  MapCompileArtifact,
  MapCompileDiagnostic,
  MapCompileInputAsset,
  MapCompileQuality,
  MapCompileRequest,
  MapCompileResult,
  MapCompileStatus,
  MapCompileArtifactKind,
  MapCompileLog,
  MapCompiler,
  MapCompilerBackend,
  MapBuildCapabilities,
  MapBuildProfileCapability,
  MapBuildService,
  MapLaunchProfileCapability,
  MapLaunchRequest,
  MapLaunchResult,
} from './compiler.js';
export {
  applyCollaborationOperation,
  collaborationEditsBetween,
  COLLABORATION_SCHEMA_VERSION,
  inverseCollaborationEdits,
  OrderedCollaborationReplica,
  simulateCollaborationDelivery,
  type CollaborationApplyResult,
  type CollaborationConflict,
  type CollaborationEdit,
  type CollaborationOperation,
  type SequencedCollaborationOperation,
  type CollaborationSimulationResult,
} from './collaboration.js';
export {
  BoundsSpatialIndex,
  type BoundsSpatialEntry,
  type SpatialRayHit,
} from './spatial-index.js';
export {
  createObjectClipboardDocument,
  FACE_ATTRIBUTE_CLIPBOARD_HEADER,
  objectClipboardBounds,
  objectClipboardPasteOffset,
  parseFaceAttributeClipboard,
  serializeFaceAttributeClipboard,
  serializeObjectClipboard,
  type FaceAttributeClipboard,
} from './clipboard.js';
export { MapCompileCoordinator, type MapCompileOutcome } from './compile-coordinator.js';
export {
  parseLeakPath,
  parsePortalFile,
  type ParsedBuildPath,
  type ParsedPortalFile,
} from './build-artifacts.js';
export { projectedFaceGridSegments, type ConstructionGridSegment } from './construction-grid.js';
export {
  deriveEntityLinks,
  selectedEntityIdsForLinks,
  visibleEntityLinks,
  type EntityLink,
  type EntityLinkMode,
  type EntityLinkProperty,
} from './entity-links.js';
export {
  EntityDefinitionCatalog,
  parseEntityDefinitionFile,
  type EntityDefinition,
  type EntityDefinitionDiagnostic,
  type EntityPropertyChoice,
  type EntityPropertyDefinition,
  type EntityPropertyType,
  type ParsedEntityDefinitionFile,
} from './entity-definitions.js';
export {
  applyEditorIssueFix,
  deriveEditorIssues,
  EDITOR_ISSUE_TYPE_INFO,
  selectionForEditorIssue,
  type EditorIssue,
  type EditorIssueCategory,
  type EditorIssueFixResult,
  type EditorIssueSeverity,
  type EditorIssueType,
} from './issues.js';
export {
  addBrushVertex,
  alignFaceTexture,
  cloneBrush,
  clipBrush,
  convexMergeBrushes,
  createBoxBrush,
  createConvexHullBrush,
  createBrushEntity,
  createEmptyDocument,
  createStarterDocument,
  deleteBrushVertices,
  flipBrush,
  defaultTextureProjection,
  insertBrush,
  insertBrushes,
  insertEntity,
  hollowBrush,
  intersectBrushes,
  moveBrushFace,
  moveBrushVertices,
  snapBrushVerticesToGrid,
  rotateBrush,
  rotateBrushVertices,
  removeBrush,
  removeBrushes,
  removeEntities,
  moveBrushesToEntity,
  replaceEntityProperties,
  replaceEntities,
  replaceBrush,
  replaceBrushes,
  replaceBrushSequence,
  replaceBrushSequences,
  setBrushFaceMaterials,
  setBrushMaterial,
  setFaceTextureTransform,
  transformFaceTexture,
  shearBrush,
  shearBrushVertices,
  splitBrushFace,
  subtractBrush,
  scaleBrush,
  scaleBrushVertices,
  transformBrush,
  transferFaceAttributes,
  translateBrush,
  type FaceTextureTransform,
  type FaceTextureTransformDelta,
  type FaceTextureAlignmentOperation,
  type FaceTextureAlignmentOptions,
  type FaceTextureFitMode,
  type FaceAttributeTransferMode,
  type FaceAttributeSource,
  type BrushInsertion,
  type BrushSequenceReplacement,
  type BrushClipSide,
  type TransformAxis,
} from './document.js';
export {
  deriveBrush,
  brushVertices,
  intersectBrushRay,
  textureCoordinates,
  type BrushRayHit,
} from './geometry.js';
export {
  brushDefToBrush,
  deriveBrushDef,
  derivePatch,
  type DerivedPatch,
  type DerivedPatchVertex,
} from './primitive-geometry.js';
export {
  MapParseError,
  mapSourceFingerprint,
  parseMap,
  parseMapFragment,
  parseMapSource,
} from './map-parser.js';
export {
  documentCodecForFormat,
  QUAKE_MAP_DOCUMENT_CODEC,
  type MapDocumentCodec,
  type QuakeMapDocumentCodec,
} from './document-codecs.js';
export {
  BUILTIN_POINT_ENTITY_DEFINITIONS,
  formatEntityOrigin,
  flipPointEntity,
  intersectPointEntityRay,
  parseEntityOrigin,
  pointEntitiesInDocument,
  pointEntityBounds,
  pointEntityDefinition,
  pointEntityYawDegrees,
  rotatePointEntity,
  transformPointEntityAffine,
  type PointEntityTransformMatrix,
  type PointEntityDefinition,
  type PointEntityRayHit,
} from './point-entities.js';
export {
  correspondingLinkedEntity,
  createLinkedGroupDuplicate,
  deriveLinkedGroupSets,
  flipAffineMatrix,
  formatGroupTransformation,
  IDENTITY_AFFINE_MATRIX,
  invertAffineMatrix,
  linkedGroupCenter,
  linkedGroupForSelection,
  linkedGroupSiblings,
  multiplyAffineMatrices,
  normalizeSingleLinkedGroups,
  parseGroupTransformation,
  protectedEntityProperties,
  rotationAffineMatrix,
  scaleAffineMatrix,
  setEntityPropertyProtection,
  shearAffineMatrix,
  synchronizeLinkedGroupContents,
  transformAffinePoint,
  transformEditorGroupMetadata,
  transformEditorGroupSubtreeMetadata,
  translationAffineMatrix,
  TRENCHBROOM_GROUP_TRANSFORMATION,
  TRENCHBROOM_LINKED_GROUP_ID,
  TRENCHBROOM_PROTECTED_PROPERTIES,
  unlinkEditorGroup,
  type AffineMatrix,
  type LinkedGroupSet,
} from './linked-groups.js';
export {
  createEditorLayer,
  deriveEditorLayers,
  documentWithoutOmittedLayers,
  editorLayerForSelection,
  findEditorLayer,
  isEditorLayerEntity,
  moveSelectionToEditorLayer,
  removeEditorLayer,
  renameEditorLayer,
  reorderEditorLayer,
  selectionForEditorLayer,
  setEditorLayerFlag,
  TRENCHBROOM_LAYER_HIDDEN,
  TRENCHBROOM_LAYER_LOCKED,
  TRENCHBROOM_LAYER_OMIT_FROM_EXPORT,
  TRENCHBROOM_LAYER_PROPERTY,
  TRENCHBROOM_LAYER_SORT_INDEX,
  TRENCHBROOM_LAYER_TYPE,
  type EditorLayer,
  type EditorLayerFlag,
  type EditorLayerId,
  type LayerCreationResult,
} from './layers.js';
export {
  stampBrushFace,
  sweepBrushFace,
  type SweepOptions,
  type SweepPath,
  type SweepResult,
  type SweepTransform,
} from './sweep.js';
export {
  DEFAULT_EDITOR_VIEW_FILTER_STATE,
  deriveEditorViewFilterObjectIds,
  EDITOR_SPECIAL_BRUSH_FILTER_INFO,
  entityClassFiltersInDocument,
  type EditorEntityClassFilter,
  type EditorSpecialBrushFilter,
  type EditorViewFilterObjectIds,
  type EditorViewFilterState,
} from './view-filters.js';
export {
  brushIdsWithMaterial,
  faceReferencesWithMaterial,
  materialUsageInDocument,
  type EditorMaterialUsage,
} from './material-usage.js';
export {
  createSimpleShapeBrushes,
  DEFAULT_SIMPLE_SHAPE_OPTIONS,
  type CircleMode,
  type SimpleShapeKind,
  type SimpleShapeOptions,
  type StairDirection,
} from './shapes.js';
export {
  RemoteMapCompiler,
  type CompilerFetch,
  type RemoteMapCompilerOptions,
} from './remote-compiler.js';
export { planMapSave, rebaseMapSource } from './map-save.js';
export {
  serializeMap,
  serializeMapBrush,
  serializeMapBrushDef,
  serializeMapEntity,
  serializeMapFace,
  serializeMapPatch,
  serializeMapPrimitive,
} from './map-serializer.js';
export type {
  MapSavePlan,
  MapSourceDiagnostic,
  MapSourceState,
  ParsedMapSource,
} from './map-source-types.js';
export {
  parseWorldviewProject,
  serializeWorldviewProject,
  WorldviewProjectParseError,
  type EntityDefinitionFormat,
  type WorldviewEntityDefinitionSource,
  type WorldviewProjectBuildProfile,
  type WorldviewProjectManifest,
  type WorldviewProjectResources,
} from './worldview-project.js';
export {
  WORLDVIEW_GAME_PROFILES,
  gameProfileSupportsFaceSyntax,
  isWorldviewGameProfile,
  worldviewGameProfile,
  type WorldviewGameProfile,
  type WorldviewGameProfileDefinition,
} from './game-profiles.js';
export {
  orderAssetMounts,
  type AssetMountDescriptor,
  type AssetMountKind,
  type BrowserWadAssetMount,
  type BuiltinAssetMount,
  type ProjectWadAssetMount,
} from './asset-mounts.js';
export {
  connectedCoplanarFaces,
  createBrushSelection,
  createFaceSelection,
  createObjectSelection,
  facesOfBrush,
  isBrushSelected,
  isFaceSelected,
  isPointEntitySelected,
  matchingBrushFaces,
  selectedBrushIds,
  selectedFaceReferences,
  selectedPointEntityIds,
  updateBrushSelection,
  updateFaceSelection,
  updatePointEntitySelection,
  type ObjectSelectionPrimary,
} from './selection.js';
export {
  querySelectionBrushes,
  type SelectionBrushProjection,
  type SelectionBrushQueryMode,
  type SelectionBrushQueryOptions,
  type SelectionBrushQueryResult,
} from './selection-query.js';
export {
  deriveEditorGroups,
  deleteEditorGroup,
  editorGroupForObject,
  groupObjects,
  isEditorGroupEntity,
  moveObjectsIntoEditorGroup,
  renameEditorGroup,
  selectedEditorGroup,
  selectionForEditorGroup,
  TRENCHBROOM_GROUP_TYPE,
  ungroupObjects,
  type EditorGroup,
  type GroupDocumentResult,
} from './groups.js';
export {
  encodeQuakeWad2,
  EditorMaterialCatalog,
  type EditorMaterial,
  type MaterialImportDiagnostic,
  type MaterialImportResult,
} from './materials.js';
export {
  EditorSession,
  type DocumentEditCandidate,
  type BrushBatchCreationCandidate,
  type SweepCandidate,
  type BrushBatchEditCandidate,
  type BrushBatchClipCandidate,
  type BrushClipCandidate,
  type BrushClipEdit,
  type BrushClipMode,
  type BrushCreationCandidate,
  type BrushEdit,
  type BrushEditCandidate,
  type BrushSequenceCandidate,
  type EditorSessionChange,
  type EditorRepeatableCommand,
  type SelectionBrushSelectionResult,
} from './session.js';
export {
  brushesInDocument,
  brushDefsInDocument,
  brushesInEntity,
  primitivesInDocument,
  patchesInDocument,
  createSequentialIdFactory,
  findBrush,
  findPrimitive,
  isMapBrush,
  type Bounds,
  type BrushId,
  type BrushDefId,
  type BrushSelection,
  type DerivedBrush,
  type DerivedEdge,
  type DerivedFace,
  type DocumentId,
  type EntityId,
  type EditorObjectViewState,
  type EditorSelection,
  type FaceId,
  type FaceSelection,
  type GeometryDiagnostic,
  type IdFactory,
  type MapBrush,
  type MapBrushDef,
  type MapBrushDefFace,
  type MapPrimitive,
  type MapPatch,
  type MapPatchPoint,
  type MapDocument,
  type MapEntity,
  type MapFace,
  type MapFragment,
  type MapDocumentFormat,
  type MapFaceSyntax,
  type SurfaceAttributes,
  type TextureProjection,
  type Vec2,
  type Vec3,
  type PointEntitySelection,
  type PrimitiveId,
  type PatchId,
} from './types.js';
